# Generated by Django 5.0.1 on 2024-09-19 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('NONE', 'No Authentication'), ('API_KEY', 'API Key'), ('BASIC', 'Basic Authentication'), ('BEARER', 'Bearer Token (OAuth)'), ('CUSTOM', 'Custom Authentication')], default='NONE', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_username', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_password', models.CharField(blank=True, max_length=255, null=True)),
                ('bearer_token', models.TextField(blank=True, null=True)),
                ('custom_auth_headers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraphQLAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphql_query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphQLAPIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphql_errors', models.JSONField(blank=True, null=True)),
                ('graphql_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='GET', max_length=10)),
                ('expected_status_code', models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestAPIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apiName', models.CharField(max_length=255)),
                ('apiType', models.CharField(choices=[('REST', 'REST API'), ('GraphQL', 'GraphQL API')], max_length=50)),
                ('apiUrl', models.URLField()),
                ('apiCallInterval', models.IntegerField(default=5)),
                ('expectedResponseTime', models.IntegerField(default=10)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipientDl', models.EmailField(max_length=254)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.businessunit')),
                ('graphqlApiconfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.graphqlapiconfig')),
                ('subBusinessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.subbusinessunit')),
                ('restApiConfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.restapiconfig')),
            ],
        ),
    ]
