# Generated by Django 5.0.1 on 2024-11-21 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('NONE', 'No Authentication'), ('API_KEY', 'API Key'), ('BASIC', 'Basic Authentication'), ('BEARER', 'Bearer Token (OAuth)')], default='NONE', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_username', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_password', models.CharField(blank=True, max_length=254, null=True)),
                ('bearer_token', models.TextField(blank=True, null=True)),
                ('custom_auth_headers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apiName', models.CharField(blank=True, max_length=255, null=True)),
                ('apiUrl', models.URLField()),
                ('apiCallInterval', models.IntegerField(blank=True, default=5, null=True)),
                ('expectedResponseTime', models.IntegerField(blank=True, default=10, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('methodType', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('requestBody', models.TextField(blank=True, null=True)),
                ('isApiActive', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipientDl', models.JSONField()),
                ('createdBy', models.EmailField(blank=True, max_length=254, null=True)),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.businessunit')),
                ('subBusinessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.subbusinessunit')),
                ('taskId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('requestStartTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstByteTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('responseTime', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('statusCode', models.IntegerField(blank=True, null=True)),
                ('responseSize', models.IntegerField(default=233)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ApiMonitoring.monitoredapi')),
            ],
        ),
    ]
