# Generated by Django 5.0.1 on 2024-01-18 08:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0001_initial'),
        ('Business', '0002_alter_businessunit_id_alter_subbusinessunit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbusinessunit',
            name='businessUnitId',
        ),
        migrations.CreateModel(
            name='ApiRequestDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apiName', models.CharField(max_length=100)),
                ('apiUrl', models.CharField(max_length=100)),
                ('expectedResponseTime', models.IntegerField()),
                ('requestPayload', models.JSONField()),
                ('apiCallInterval', models.IntegerField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.EmailField(blank=True, max_length=254)),
                ('recipientDl', models.EmailField(max_length=254)),
                ('BusinessUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.businessunit')),
                ('subBusinessUnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.subbusinessunit')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='SubBusinessUnit',
        ),
    ]
