# Generated by Django 5.0.1 on 2024-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapi',
            name='lastModifiedBy',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='apimetrics',
            name='responseSize',
            field=models.IntegerField(default=233),
        ),
        migrations.AlterField(
            model_name='monitoredapi',
            name='createdBy',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='restapiconfig',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
