# Generated by Django 5.0.1 on 2024-09-30 14:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphqlapiconfig',
            name='graphql_value',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='apiMonitorDuration',
        ),
        migrations.RemoveField(
            model_name='restapiconfig',
            name='expected_status_code',
        ),
        migrations.AddField(
            model_name='apimetrics',
            name='firstByteTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apimetrics',
            name='requestStartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apimetrics',
            name='responseSize',
            field=models.IntegerField(default=230),
        ),
        migrations.AlterField(
            model_name='apimetrics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apimetrics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
