# Generated by Django 5.0.1 on 2024-09-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphQLAPIMetrics',
        ),
        migrations.DeleteModel(
            name='RestAPIMetrics',
        ),
        migrations.RemoveField(
            model_name='restapiconfig',
            name='expected_status_code',
        ),
    ]
