# Generated by Django 5.0.1 on 2024-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0002_delete_graphqlapimetrics_delete_restapimetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restapiconfig',
            name='expected_status_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
