# Generated by Django 5.0.1 on 2024-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0002_remove_monitoredapi_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapi',
            name='taskId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
