# Generated by Django 5.0.1 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0002_remove_monitoredapi_graphqlapiconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertionandlimit',
            name='regex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
