# Generated by Django 5.0.1 on 2024-11-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0002_monitoredapi_methodtype_monitoredapi_requestbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredapi',
            name='apiType',
        ),
    ]
