# Generated by Django 5.0.1 on 2024-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0002_monitoredapi_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'No Authentication'), ('BASIC', 'Basic Authentication'), ('BEARER', 'Bearer Token (OAuth)')], default='NONE', max_length=50),
        ),
    ]
