# Generated by Django 5.0.1 on 2024-09-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0003_authentication_graphqlapiconfig_graphqlapimetrics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiRequestDetails',
        ),
    ]
