# Generated by Django 5.0.1 on 2024-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0003_restapiconfig_expected_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapi',
            name='apiCallInterval',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredapi',
            name='apiName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredapi',
            name='expectedResponseTime',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
