# Generated by Django 5.0.1 on 2025-02-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0003_assertionandlimit_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertionandlimit',
            name='operator',
            field=models.CharField(blank=True, choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], max_length=20, null=True),
        ),
    ]
