# Generated by Django 5.0.1 on 2024-09-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0004_alter_monitoredapi_apicallinterval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('responseTime', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('statusCode', models.IntegerField(blank=True, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ApiMonitoring.monitoredapi')),
            ],
        ),
    ]
