# Generated by Django 5.0.1 on 2024-12-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0003_monitoredapi_taskid'),
        ('ApiMonitoring', '0004_alter_authentication_auth_type'),
    ]

    operations = [
    ]
