# Generated by Django 5.0.1 on 2024-09-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0004_delete_apirequestdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restapimetrics',
            name='response_payload',
        ),
    ]
