# Generated by Django 5.0.1 on 2024-11-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0004_remove_monitoredapi_graphqlapiconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphQLAPIConfig',
        ),
        migrations.DeleteModel(
            name='RestAPIConfig',
        ),
    ]
