# Generated by Django 5.0.1 on 2024-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0005_delete_graphqlapiconfig_delete_restapiconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapi',
            name='recipientDl',
            field=models.TextField(),
        ),
    ]
