# Generated by Django 5.0.1 on 2024-09-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0006_monitoredapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredapi',
            name='authentication',
        ),
    ]
