# Generated by Django 5.0.1 on 2024-09-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0007_remove_monitoredapi_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredapi',
            name='graphqlApiconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.graphqlapiconfig'),
        ),
        migrations.AlterField(
            model_name='monitoredapi',
            name='restApiConfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.restapiconfig'),
        ),
    ]
