# Generated by Django 5.0.1 on 2024-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0008_monitoredapi_teamschannelwebhookurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapi',
            name='maxRetries',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='monitoredapi',
            name='retryAfter',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
