# Generated by Django 5.0.1 on 2025-01-15 13:19
# Generated by Django 5.0.1 on 2025-01-14 07:16

from django.db import migrations
from ApiMonitoring.Model.ApiMonitoringModel.apiMonitorModels import MonitoredAPI
from ApiMonitoring.Model.ApiMonitoringModel.assertionAndLimitModels import AssertionAndLimit
from ApiMonitoring.Model.ApiMonitoringModel.schedulingAndAlertingModels import SchedulingAndAlerting


def migrate_data(apps, schema_editor):

    for monitor in MonitoredAPI.objects.all():
        AssertionAndLimit.objects.create(
            api=monitor,
        )
        if hasattr(monitor, 'apiCallInterval') and hasattr(monitor, 'maxRetries') and hasattr(monitor, 'retryAfter') and hasattr(monitor, 'recipientDl') and hasattr(monitor, 'createdBy') and hasattr(monitor, 'teamsChannelWebhookURL'):
            required_fields = [
                monitor.apiCallInterval,
                monitor.maxRetries,
                monitor.retryAfter,
                monitor.recipientDl,
                monitor.createdBy,
                monitor.teamsChannelWebhookURL,
            ]

            if all(field is not None for field in required_fields):
                SchedulingAndAlerting.objects.create(
                    api=monitor,
                    apiCallInterval=monitor.apiCallInterval,
                    maxRetries = monitor.maxRetries,
                    retryAfter = monitor.retryAfter,
                    recipientDl = monitor.recipientDl,
                    createdBy = monitor.createdBy,
                    teamsChannelWebhookURL = monitor.teamsChannelWebhookURL
                )


class Migration(migrations.Migration):
    dependencies = [
        ('ApiMonitoring', '0010_remove_monitoredapi_apicallinterval_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]



