# Generated by Django 5.0.1 on 2025-01-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0011_auto_20250115_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredapi',
            name='apiCallInterval',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='expectedResponseTime',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='maxRetries',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='recipientDl',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='retryAfter',
        ),
        migrations.RemoveField(
            model_name='monitoredapi',
            name='teamsChannelWebhookURL',
        ),
    ]
