# Generated by Django 5.0.1 on 2025-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0012_remove_monitoredapi_apicallinterval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assertionandlimit',
            name='degradedResponseTime',
        ),
        migrations.RemoveField(
            model_name='assertionandlimit',
            name='failedResponseTime',
        ),
        migrations.AddField(
            model_name='assertionandlimit',
            name='expectedValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assertionandlimit',
            name='operator',
            field=models.CharField(blank=True, choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('contains', 'Contains')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assertionandlimit',
            name='property',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assertionandlimit',
            name='source',
            field=models.CharField(blank=True, choices=[('status_code', 'Status Code'), ('headers', 'Headers'), ('body', 'JSON Body')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoredapi',
            name='degradedResponseTime',
            field=models.IntegerField(blank=True, help_text='Threshold in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='monitoredapi',
            name='failedResponseTime',
            field=models.IntegerField(blank=True, help_text='Threshold in milliseconds', null=True),
        ),
        migrations.AddConstraint(
            model_name='assertionandlimit',
            constraint=models.UniqueConstraint(fields=('api', 'source', 'property', 'operator'), name='unique_assertion_per_api'),
        ),
    ]
