# Generated by Django 5.0.1 on 2025-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0013_remove_assertionandlimit_degradedresponsetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertionandlimit',
            name='source',
            field=models.CharField(blank=True, choices=[('status_code', 'Status Code'), ('headers', 'Headers'), ('json_body', 'JSON Body')], max_length=50, null=True),
        ),
    ]
