# Generated by Django 5.0.1 on 2025-02-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0014_alter_assertionandlimit_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assertionandlimit',
            name='unique_assertion_per_api',
        ),
    ]
