# Generated by Django 5.0.1 on 2025-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0015_remove_assertionandlimit_unique_assertion_per_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertionAndLimitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.TextField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('apimetrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.apimetrics')),
                ('assertion_and_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiMonitoring.assertionandlimit')),
            ],
        ),
    ]
