# Generated by Django 5.0.1 on 2025-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0016_assertionandlimitresult'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assertionandlimit',
            constraint=models.UniqueConstraint(fields=('api', 'source', 'property', 'operator'), name='unique_assertion_per_api'),
        ),
    ]
