# Generated by Django 5.0.1 on 2025-02-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMonitoring', '0017_assertionandlimit_unique_assertion_per_api'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assertionandlimit',
            name='unique_assertion_per_api',
        ),
    ]
