# Generated by Django 5.0.1 on 2024-09-24 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('businessUnitName', models.CharField(max_length=50)),
                ('businessUnitDescription', models.CharField(max_length=100)),
                ('businessUnitDl', models.EmailField(max_length=254)),
                ('createdBy', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubBusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subBusinessUnitName', models.CharField(max_length=50)),
                ('subBusinessUnitDescription', models.CharField(max_length=100)),
                ('subBusinessUnitDl', models.EmailField(max_length=254)),
                ('createdBy', models.EmailField(max_length=254)),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.businessunit')),
            ],
        ),
    ]
