# Generated by Django 5.0.1 on 2025-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='subbusinessunit',
            name='createdBy',
        ),
    ]
